'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>(100*x).toFixed(1)+'%',num=x=>(x>=0?'+':'')+x.toFixed(3), fmt=x=>Number(x).toLocaleString();
const names={FF:'Four-seam',SI:'Sinker',FC:'Cutter',SL:'Slider',ST:'Sweeper',CU:'Curveball',KC:'Knuckle curve',CH:'Changeup',FS:'Splitter',SV:'Slurve',FO:'Forkball',KN:'Knuckleball'};
let roster,mode='realistic',pitch='',target=[0,2.5],analysis=null,surface=null,history=[],last=null,ended=false,busy=false,version=0,view='game',timer;
async function request(url,body){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});if(!r.ok){let j=await r.json();throw Error(typeof j.detail==='string'?j.detail:'The request could not be completed. Check the selected inputs.')}return r.json()}
function notice(t,error=false){$('notice').textContent=t;$('notice').classList.toggle('error',error)}
function context(){return {pitcher:$('pitcher').value,hitter:$('hitter').value,pitch,balls:+$('balls').value,strikes:+$('strikes').value,outs:+$('outs').value,bases:+$('bases').value,x:target[0],z:target[1],mode}}
function pitcher(){return roster.pitchers.find(p=>p.id===$('pitcher').value)}function hitter(){return roster.hitters.find(p=>p.id===$('hitter').value)}
function setBusy(b){busy=b;$('throw').disabled=b||ended;$('optimize').disabled=b;['pitcher','hitter','balls','strikes','outs','bases','reset','realistic','perfect','pitcherSearch','hitterSearch'].forEach(id=>$(id).disabled=b);document.querySelectorAll('.pitch').forEach(el=>el.disabled=b)}
function support(n){return n>=600?'HIGH':n>=150?'MEDIUM':'LIMITED'}
function renderPlayers(kind,query=''){
 const list=roster[kind==='pitcher'?'pitchers':'hitters'],sel=$(kind),old=sel.value,items=list.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 sel.innerHTML=items.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(items.some(p=>p.id===old))sel.value=old;
 if(!items.length){sel.innerHTML='<option value="">No matching players</option>';$('throw').disabled=true;return false}return true;
}
function renderMatchup(){
 const p=pitcher(),h=hitter();if(!p||!h)return;
 $('pitcherMeta').textContent=`${p.hand}HP · ${fmt(p.n)} training pitches · ${p.outings} outings`;
 $('hitterMeta').textContent=`${h.switch?'Switch':h.hand+'-handed'} · ${fmt(h.n)} pitches seen · ${h.pa} PA`;
 if(!p.pitches.some(v=>v.type===pitch))pitch=p.pitches.slice().sort((a,b)=>b.usage-a.usage)[0].type;
 $('pitches').innerHTML=p.pitches.map(v=>`<button class="pitch ${pitch===v.type?'active':''}" data-pitch="${esc(v.type)}" title="${esc(names[v.type]||v.type)}"><b>${esc(names[v.type]||v.type)}</b><small>${v.mean_velocity?.toFixed(1)||'—'} MPH · ${pct(v.usage)}</small></button>`).join('');
 document.querySelectorAll('[data-pitch]').forEach(b=>b.onclick=()=>{if(busy)return;pitch=b.dataset.pitch;last=null;renderMatchup();schedule()});
 const c=p.pitches.find(v=>v.type===pitch).command;$('support').textContent=support(c.n)+' SUPPORT';$('countDisplay').textContent=$('balls').value+' – '+$('strikes').value;
 draw();
}
const px=x=>250+x*120,pz=z=>490-(z-.5)*120;
function draw(){
 if(!roster)return;const h=hitter();if(!h)return;const top=h.zone_top||3.5,bottom=h.zone_bottom||1.5;let s='';
 for(let x=-1.5;x<=1.5;x+=.5)s+=`<line x1="${px(x)}" y1="40" x2="${px(x)}" y2="460" stroke="#223143" stroke-dasharray="2 5"/>`;
 for(let z=1;z<=4;z+=.5)s+=`<line x1="70" y1="${pz(z)}" x2="430" y2="${pz(z)}" stroke="#223143" stroke-dasharray="2 5"/><text x="47" y="${pz(z)+4}" fill="#738398" font-size="11" font-family="monospace">${z.toFixed(1)}</text>`;
 const locs=analysis?.[mode]?.locations||[];for(const [x,z] of locs)if(px(x)>=35&&px(x)<=465&&pz(z)>=20&&pz(z)<=470)s+=`<circle cx="${px(x)}" cy="${pz(z)}" r="2" fill="#70a9cf" opacity=".35"/>`;
 const profile=pitcher().pitches.find(p=>p.type===pitch)?.command;
 if(mode==='realistic'&&profile){const [a,b]=profile.covariance[0],[,d]=profile.covariance[1],disc=Math.sqrt((a-d)**2+4*b*b),l1=(a+d+disc)/2,l2=(a+d-disc)/2,angle=-Math.atan2(2*b,a-d)*90/Math.PI;for(const cover of [.8,.5]){const q=-2*Math.log(1-cover),rx=Math.sqrt(l1*q)*10,ry=Math.sqrt(l2*q)*10;s+=`<ellipse cx="${px(target[0]+profile.mean[0]/12)}" cy="${pz(target[1]+profile.mean[1]/12)}" rx="${rx}" ry="${ry}" fill="none" stroke="#70a9cf" stroke-opacity="${cover===.8?.35:.6}" stroke-dasharray="${cover===.8?'4 5':'0'}" transform="rotate(${angle} ${px(target[0]+profile.mean[0]/12)} ${pz(target[1]+profile.mean[1]/12)})"/>`}}
 s+=`<rect x="165" y="${pz(top)}" width="170" height="${(top-bottom)*120}" fill="#0b111b22" stroke="#c8d2dd" stroke-width="1.5"/>`;
 for(let i=1;i<3;i++){s+=`<line x1="${165+170*i/3}" y1="${pz(top)}" x2="${165+170*i/3}" y2="${pz(bottom)}" stroke="#9babbf55"/><line x1="165" y1="${pz(top-(top-bottom)*i/3)}" x2="335" y2="${pz(top-(top-bottom)*i/3)}" stroke="#9babbf55"/>`}
 s+=`<circle cx="${px(target[0])}" cy="${pz(target[1])}" r="11" fill="#ffae6818" stroke="#ffae68" stroke-width="2"/><path d="M${px(target[0])-18} ${pz(target[1])}h10m16 0h10M${px(target[0])} ${pz(target[1])-18}v10m0 16v10" stroke="#ffae68" stroke-width="1.5"/>`;
 if(last)s+=`<circle class="landing" cx="${px(last[0])}" cy="${pz(last[1])}" r="6" fill="white" stroke="#0b111b" stroke-width="2"/>`;
 s+=`<text x="250" y="24" text-anchor="middle" fill="#738398" font-size="11" font-family="monospace">${target[0].toFixed(2)} X / ${target[1].toFixed(2)} Z</text><text x="250" y="486" text-anchor="middle" fill="#738398" font-size="10">Estimated historical strike zone · arrows also move target</text>`;$('zone').innerHTML=s;
}
function schedule(){clearTimeout(timer);timer=setTimeout(update,180)}
async function update(){if(!pitcher()||!hitter())return;const v=++version;setBusy(true);notice('Calculating the landing distribution…');try{const a=await request('/api/analyze',context());if(v!==version)return;analysis=a;renderAnalysis();draw();notice(`${fmt(roster.pitchers.length)} pitchers · ${fmt(roster.hitters.length)} hitters · Research models, not a validated coaching system`)}catch(e){notice(e.message,true)}finally{if(v===version)setBusy(false)}}
function renderAnalysis(){const a=analysis[mode];const calibration=analysis.command_validation;const targetNote=a.target_support;const cell=pitcher().pitches.find(p=>p.type===pitch).command;$('support').textContent=!targetNote.supported?'LIMITED TARGET SUPPORT':calibration&&Math.abs(calibration.coverage80-.8)>.05?'LIMITED CALIBRATION':support(cell.n)+' SUPPORT';$('swing').textContent=pct(a.swing);$('whiff').textContent=pct(a.whiff_given_swing);$('swingBar').style.width=pct(a.swing);$('whiffBar').style.width=pct(a.whiff_given_swing);$('rv').textContent=num(a.run_value);$('perfectValue').textContent=num(analysis.perfect.run_value);$('realValue').textContent=num(analysis.realistic.run_value);$('penalty').textContent=num(analysis.command_penalty);
 const c=pitcher().pitches.find(p=>p.type===pitch).command;$('advanced').innerHTML=`<p>${targetNote.n} training targets within 0.5 ft of the nearest grid target. ${targetNote.supported?'Eligible for target comparison.':'Sparse target region: treat estimates as extrapolation; optimizer excludes this grid region.'}</p><p>${calibration?`Pitcher-level held-out 80% coverage: ${pct(calibration.coverage80)} across ${fmt(calibration.n)} pitches. This pools the pitcher’s pitch types.`:'No qualifying pitcher-level validation subgroup.'}</p><p>${fmt(c.n)} command observations; ${support(c.n).toLowerCase()} sample support. Support uses observed sample count, not a calibrated confidence guarantee.</p><p>Mean miss: ${c.mean[0].toFixed(1)}″ horizontal, ${c.mean[1].toFixed(1)}″ vertical.<br>Standard deviation: ${Math.sqrt(c.covariance[0][0]).toFixed(1)}″ / ${Math.sqrt(c.covariance[1][1]).toFixed(1)}″.</p><p>Conditional contact estimates: ${a.exit_velocity_given_in_play.toFixed(1)} mph exit velocity; ${a.xwoba_given_in_play.toFixed(3)} xwOBA.</p><p>Integration SE: ${a.integration_se.toFixed(4)} runs. This measures numerical uncertainty only; model and target-measurement uncertainty are larger and not quantified here. Ellipses show 50% and 80% fitted landing regions.</p>`}
function reset(recalculate=true){history=[];ended=false;last=null;surface=null;$('maps').innerHTML='';$('balls').value=0;$('strikes').value=0;$('result').textContent='';$('score').textContent='';$('paStatus').textContent='Waiting for the first call';$('recommendation').textContent='';renderHistory();if(roster){renderMatchup();if(recalculate)schedule()}}
function renderHistory(){if(!history.length){$('history').innerHTML='<p class="empty">Your pitch-by-pitch decisions will appear here.</p>';return}const rows=history.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${esc(names[r.pitch]||r.pitch)}</td><td>${r.count}</td><td>${r.target.map(x=>x.toFixed(2)).join(', ')}</td><td>${esc(r.event.replaceAll('_',' '))}</td><td>${num(r.expected.run_value)}</td><td>${r.decision_loss.toFixed(3)}</td><td>${esc(names[r.optimal.pitch]||r.optimal.pitch)} · ${r.optimal.target.map(x=>x.toFixed(2)).join(', ')}</td></tr>`).join('');$('history').innerHTML=`<table><thead><tr><th>#</th><th>CALL</th><th>COUNT</th><th>TARGET (FT)</th><th>RESULT</th><th>EXPECTED RV</th><th>DECISION LOSS</th><th>GRID ALTERNATIVE</th></tr></thead><tbody>${rows}</tbody></table>`}
async function optimize(){setBusy(true);notice('Comparing targets across the repertoire…');try{surface=await request('/api/surface',context());const best=surface['best_'+mode];$('recommendation').textContent=`Best modeled call: ${names[best.pitch]||best.pitch} at (${best.target.map(x=>x.toFixed(2)).join(', ')}) feet. Expected offensive value ${num(best[mode])} runs. Best among the tested grid, subject to model error.`;if(view==='pro')renderMaps();notice(surface.grid_note)}catch(e){notice(e.message,true)}finally{setBusy(false)}}
function renderMaps(){if(!surface)return;const metric=$('mapMetric').value,val=c=>metric==='penalty'?c.realistic-c.perfect:c[metric],all=surface.cells.map(val),lo=Math.min(...all),hi=Math.max(...all);$('maps').innerHTML=pitcher().pitches.map(p=>{const cells=surface.cells.filter(c=>c.pitch===p.type);return `<article class="mapcard"><h3>${esc(names[p.type]||p.type)}</h3><svg viewBox="0 0 210 265" aria-label="${esc(metric)} map">${cells.map(c=>{const t=(val(c)-lo)/(hi-lo||1),r=Math.round(39+191*t),g=Math.round(80+81*t),b=Math.round(110-15*t);return `<rect x="${10+(c.target[0]+1.5)*60}" y="${10+(4.25-c.target[1])*60}" width="20" height="19" fill="rgb(${r},${g},${b})" opacity="${c.target_support.supported?1:.2}"><title>${esc(p.type)} (${c.target.join(', ')}): ${val(c).toFixed(4)}</title></rect>`}).join('')}<rect x="57.5" y="65" width="85" height="120" fill="none" stroke="white" stroke-opacity=".7"/></svg><p>Faded cells have limited target support. Shared scale: ${lo.toFixed(3)} (blue) → ${hi.toFixed(3)} (orange). Reference zone shown.</p></article>`}).join('')}
async function throwPitch(){if(busy||ended)return;setBusy(true);notice('Throwing the pitch…');const c=context();c.seed=crypto.getRandomValues(new Uint32Array(1))[0];try{const r=await request('/api/throw',c);history.push({...r,pitch,count:`${c.balls}–${c.strikes}`});last=r.location;ended=r.state.ended;$('balls').value=r.state.balls;$('strikes').value=r.state.strikes;$('result').textContent=(ended?r.state.result:r.event).replaceAll('_',' ').toUpperCase();$('countDisplay').textContent=`${r.state.balls} – ${r.state.strikes}`;$('paStatus').textContent=ended?'Plate appearance complete':`Pitch ${history.length} complete`;renderHistory();draw();if(ended){const bestCall=history.reduce((a,b)=>a.decision_loss<=b.decision_loss?a:b),worstCall=history.reduce((a,b)=>a.decision_loss>=b.decision_loss?a:b);const loss=history.reduce((s,x)=>s+x.decision_loss,0),rank=history.reduce((s,x)=>s+x.decision_percentile,0)/history.length;$('score').textContent=`Decision percentile: ${rank.toFixed(0)} / 100 · ${loss.toFixed(3)} cumulative modeled runs lost vs grid choices. Best call: pitch ${history.indexOf(bestCall)+1}; largest modeled loss: pitch ${history.indexOf(worstCall)+1}. This ranks decisions, not the luck of the result.`;notice('Plate appearance complete. Review your calls or start a new matchup.')}else{surface=null;notice('Choose your next pitch and target.');schedule()}}catch(e){notice(e.message,true)}finally{setBusy(false)}}
async function showView(v){view=v;document.querySelectorAll('nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('workspace').classList.toggle('hidden',v==='method');$('historyPanel').classList.toggle('hidden',v==='method');$('pro').classList.toggle('hidden',v!=='pro');$('method').classList.toggle('hidden',v!=='method');if(v==='pro')await optimize();if(v==='method'&&!$('validation').innerHTML){try{const d=await request('/api/methodology');const c=d.command,t=c.test.pitcher_pitch_type;let html=`<h3>Observed data & held-out results</h3><p>${fmt(c.usable_regular_season)} usable command pitches. ${fmt(t.n)} held-out command observations. Nominal 80% coverage: ${pct(t.coverage_80)}. RMSE: ${t.rmse_x_inches.toFixed(2)}″ horizontal / ${t.rmse_z_inches.toFixed(2)}″ vertical.</p><table><thead><tr><th>RESPONSE MODEL</th><th>SELECTED</th><th>TEST LOG LOSS / RMSE</th><th>PLAYER-AGNOSTIC</th></tr></thead><tbody>`;for(const [k,r]of Object.entries(d.response.models)){const m=r[r.selected].test;if(k==='run_value'&&d.value){const value=d.value.models[d.value.selected];html+=`<tr><td>run value</td><td>${esc(d.value.selected)}</td><td>${value.test_rmse.toFixed(4)}</td><td>${d.value.models.tree.test_rmse.toFixed(4)} (tree)</td></tr>`;continue}html+=`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${esc(r.selected)}</td><td>${(m.log_loss??m.rmse).toFixed(4)}</td><td>${(r.agnostic.test.log_loss??r.agnostic.test.rmse).toFixed(4)}</td></tr>`}html+='</tbody></table><p>Lower is better. Separate response heads are not guaranteed to be mutually calibrated. Run-value improvement is modest; optimizing it is exploratory. Aggregate validation does not prove subgroup reliability or policy improvement.</p>';html+=`<h3>External evaluation · ${esc(d.external.dates.join(' to '))}</h3><p>${fmt(d.external.n)} pitches across ${d.external.games} previously unused games, after converting 2026 location coordinates to the 2025 reference plane. Swing log loss: ${d.external.models.swing.log_loss.toFixed(4)}. Run-value RMSE: ${d.external.models.run_value.rmse.toFixed(4)} versus ${d.external.models.run_value.linear_baseline_rmse.toFixed(4)} for the linear baseline. This is a 12-day conditional-response check, not full-season or end-to-end policy validation.</p>`;$('validation').innerHTML=html}catch(e){notice(e.message,true)}}}
$('zone').addEventListener('click',e=>{if(busy||ended)return;const p=$('zone').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform($('zone').getScreenCTM().inverse());target=[Math.max(-1.5,Math.min(1.5,(q.x-250)/120)),Math.max(.75,Math.min(4.25,.5+(490-q.y)/120))];last=null;draw();schedule()});
$('zone').addEventListener('keydown',e=>{if(busy||ended||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();target=[Math.max(-1.5,Math.min(1.5,target[0]+(e.key==='ArrowRight'?.05:e.key==='ArrowLeft'?-.05:0))),Math.max(.75,Math.min(4.25,target[1]+(e.key==='ArrowUp'?.05:e.key==='ArrowDown'?-.05:0)))];last=null;draw();schedule()});
for(const m of ['realistic','perfect'])$(m).onclick=()=>{mode=m;for(const b of ['realistic','perfect'])$(b).classList.toggle('active',b===m);if(analysis)renderAnalysis();draw();if(surface){const best=surface['best_'+mode];$('recommendation').textContent=`Best modeled call: ${names[best.pitch]||best.pitch}, ${num(best[mode])} runs.`}};
for(const kind of ['pitcher','hitter']){$(kind).onchange=()=>reset();$(kind+'Search').oninput=()=>{if(renderPlayers(kind,$(kind+'Search').value))reset()}};
for(const id of ['balls','strikes','outs','bases'])$(id).onchange=()=>{history=[];ended=false;last=null;surface=null;$('maps').innerHTML='';$('score').textContent='';$('result').textContent='';renderHistory();renderMatchup();schedule()};
$('reset').onclick=()=>reset();$('throw').onclick=throwPitch;$('optimize').onclick=optimize;$('mapMetric').onchange=renderMaps;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
(async()=>{try{roster=await request('/api/players');renderPlayers('pitcher');renderPlayers('hitter');const p=roster.pitchers.find(p=>p.name.includes('Cease')),h=roster.hitters.find(p=>p.name.includes('Guerrero'));if(p)$('pitcher').value=p.id;if(h)$('hitter').value=h.id;renderMatchup();await update()}catch(e){notice('Models are unavailable. '+e.message,true)}})();
